Fail skipped integration tests

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -94,7 +94,26 @@ jobs:
       - name: Initialize
         run: make go-mod-tidy generate
       - name: Run tests
-        run: sudo env "PATH=$PATH" go test -v -run=TestIntegration
+        shell: bash
+        run: |
+          # Create a temp file to store the JSON output
+          tmpfile=$(mktemp)
+          
+          # Stream test output to stdout and save to file for jq
+          go test -v -run='^TestIntegration' . | tee "$tmpfile"
+          
+          # Fail if any "skip" action occurs under TestIntegration/
+          go tool test2json < "$tmpfile" | jq -e '
+            select(
+              .Action == "skip" and
+              .Test == "TestIntegration"
+            )' >/dev/null && {
+                rm "$tmpfile"
+                echo "❌ TestIntegration was skipped!"
+                exit 1
+            }
+          rm "$tmpfile"
+          
   compatibility-test:
     strategy:
       matrix:
